print('a'.join('Stella'))
print('ab'.join('stella'))
print('cc'.join('I am  '))
print('c'.join('a   a'))
print('how many will it replace? here1 here2 here3'.replace('here', 'there'))
print('Sataealalaa'.split('a'))
print('sabtabeablablaba'.split('ab'))
compatible = list()
print(type(compatible))
compatible = (1, 2, 3, 4)
print(type(compatible))
lst = [1, 2, 3, 4, 5, 1, 6, 1, 7]
print(lst.index(1))
lst = ['x', 'y', 'z', 'x', 'z',]
lst.remove('x')
print(lst)
lst.remove('x')
print(lst)
tpl = (1)
print(type(tpl))
tpl = (1,)
print(type(tpl))
